//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ogrencıler
{
    using System;
    using System.Collections.Generic;
    
    public partial class FATURAMERKEZI
    {
        public int ID { get; set; }
        public string Adı { get; set; }
        public string Soyadı { get; set; }
        public string Telefon { get; set; }
        public string UrunAdı { get; set; }
        public Nullable<int> UrunAdet { get; set; }
        public Nullable<decimal> UrunFıyat { get; set; }
        public Nullable<decimal> Tutar { get; set; }
        public Nullable<System.DateTime> GırısTarıhı { get; set; }
    }
}
