//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ogrencıler
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OgrenciDersDBEntities3 : DbContext
    {
        public OgrenciDersDBEntities3()
            : base("name=OgrenciDersDBEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GırısBılgılerı> GırısBılgılerı { get; set; }
        public virtual DbSet<FATURAMERKEZI> FATURAMERKEZI { get; set; }
    }
}
